### ISSUE TITLE
Rules are automatically removed if a new one is added 

### ISSUE THREAD

**Issue by FelixGail** [OpenAlcoholics/Saufautomobil#11]

**Comment by BjoernPetersen** [comment]
The issue here is probably that only the originId is compared, but the unique flag is ignored.

**Comment by BjoernPetersen** [comment]
I can't actually reproduce this. Please elaborate on what the exact issue is here.

**Comment by BjoernPetersen** [comment]
This turned out to be a task data issue. Closing.
